raystack/charts

.github/workflows/repository.yml
README.md

This PR: 
- Adds building of helm repository on github pages using github workflow
- Action is triggered on push and pull_request on master and any release push
- Workflow is already being triggered to create helm repository [here](https://odpf.github.io/charts/index.yaml)

Building helm repository

---

README.md

This PR updates the readme and adds the details for the installation and usage of the charts from the repo

Add installation and usage details

---

stable/meteor/Chart.yaml
stable/meteor/templates/job.yaml
stable/meteor/templates/recipe-configmap.yaml
stable/meteor/templates/variables-configmap.yaml

- add a new configmap for meteor to set env vars to job's pods

feat(meteor): add new configmap for env vars

---

stable/app/.helmignore
stable/app/Chart.yaml
stable/app/templates/_helpers.tpl
stable/app/templates/configmap.yaml
stable/app/templates/deployment.yaml
stable/app/templates/ingress.yaml
stable/app/templates/service.yaml
stable/app/values.yaml

Co-authored-by: Rohil Surana <rohilsurana96@gmail.com>

feat: add base chart for service app

---

stable/app/README.md
stable/app/values.yaml

Adds readme for [app chart](https://github.com/odpf/charts/tree/main/stable/app) with Usage and Example

chore: Update readme for the app chart

---

stable/app/Chart.yaml
stable/app/templates/service.yaml
stable/app/values.yaml

feat: add capability to pass annotations in service object

---

stable/app/Chart.yaml
stable/app/templates/deployment.yaml
stable/app/values.yaml

feat(app): Expose volume mounts

---

stable/app/Chart.yaml
stable/app/templates/migration-job.yaml

it adds support to mount volumes in migration job

feat(app): Expose volume mounts in migration for app chart

---

stable/compass/Chart.yaml

to be merged after https://github.com/odpf/charts/pull/57

fix(compass): bump app version and chart version

---

stable/entropy/.helmignore
stable/entropy/Chart.lock
stable/entropy/Chart.yaml
stable/entropy/README.md
stable/entropy/values.yaml

Add Chart for [Entropy](https://github.com/odpf/entropy) deployment (based on existing Columbus chart)

feat(entropy): app chart

---

stable/optimus/.helmignore
stable/optimus/Chart.yaml
stable/optimus/templates/_helpers.tpl
stable/optimus/templates/configmap.yaml
stable/optimus/templates/deployment.yaml
stable/optimus/templates/ingress.yaml
stable/optimus/templates/secret.yaml
stable/optimus/templates/service.yaml
stable/optimus/templates/telegraf-configmap.yaml
stable/optimus/values.yaml

feat: add chart for optimus

---

stable/optimus/Chart.yaml
stable/optimus/values.yaml

Removed invalid value for hostname, added sample ingress config

chore: update ingress config values

---

stable/meteor/Chart.yaml
stable/meteor/templates/cronjob.yaml
stable/meteor/templates/secret.yaml

feat(meteor): create k8s secrets only when secretConfig is non-empty

---

stable/app/Chart.yaml
stable/app/templates/configmap.yaml
stable/app/templates/secret.yaml

Closes https://github.com/odpf/charts/issues/69

fix(app): prevents deletion of configmap and secret

---

stable/compass/Chart.lock
stable/compass/Chart.yaml

Bump latest compass's `app` dependency version to `0.4.2`

feat(compass): bump app version to 0.4.2

---

stable/app/templates/_helpers.tpl
stable/app/templates/configmap.yaml
stable/app/templates/cron.yaml
stable/app/templates/deployment.yaml
stable/app/templates/ingress.yaml
stable/app/templates/migration-job.yaml
stable/app/templates/secret.yaml
stable/app/templates/service.yaml
stable/app/templates/telegraf-configmap.yaml
stable/app/values.yaml

- add namespace from `Release.Namespace` in all templates
- support for namespaceOverride in values

feat: add namespace in all templates

---

stable/app/Chart.yaml
stable/app/README.md
stable/app/templates/_helpers.tpl
stable/app/values.yaml

Add support for additional labels in app chart

feat: add support for additional labels in app chart

---

stable/app/Chart.yaml
stable/app/templates/hpa.yaml

- Behaviour support for scaling up and down was made stable in v1.23. [Ref](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior)
- Add support for using the same in app chart

feat: add support for behaviour in hpa.

---

stable/app/Chart.yaml
stable/app/templates/deployment.yaml
stable/app/templates/poddisruptionbudget.yaml
stable/app/values.yaml

PR adds pod disruption budget, to increase fault tolerance

feat: add pdb for making pixxel services fault tolerant

---

stable/app/templates/poddisruptionbudget.yaml

The new condition checks if:
- pdb.enabled is true, and
Either:
- hpa.enabled is true and hpa.minReplicas is greater than 1, or
- replicaCount is greater than 1

patch: update pdb

---

stable/firehose/Chart.yaml
stable/firehose/templates/deployment.yaml
stable/firehose/templates/secret.yaml
stable/firehose/values.yaml

Introduces a new secret.yaml template to create Kubernetes Secrets when .Values.secretConfig is set. Updates deployment.yaml to mount the secret as environment variables, enabling secure handling of sensitive configuration.

feat: add support for secret configuration in Firehose chart
